name: birding.com
favicon: null
layout_spectrum: 0.05236374284140766
typography_spectrum: 0.9717976718675345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3249812563881278
  lightness: 0.41209690854884684
  saturation: 0.14632912375964224
  rhythmicContrast: 0.20038358261808753
purpose: []
